data:
  tokenizer: null
  val_files: ~/data/rlhf/gsm8k/test.parquet
  val_data_num: null
  prompt_key: prompt
  max_prompt_length: 512
  max_response_length: 512
  max_start_length: 256
  max_obs_length: 512
  val_batch_size: 1312
  return_raw_chat: False

actor_rollout_ref:
  hybrid_engine: True
  model:
    path: ~/models/deepseek-llm-7b-chat
    external_lib: null
    override_config: { }
    enable_gradient_checkpointing: False
    use_remove_padding: False
  actor:
    strategy: fsdp
    ppo_mini_batch_size: 256
    ppo_micro_batch_size: 64
    use_dynamic_bsz: False
    ppo_max_token_len_per_gpu: 16384
    ulysses_sequence_parallel_size: 1
    optim:
      lr: 1e-6
      lr_warmup_steps_ratio: 0.
      min_lr_ratio: null
      warmup_style: constant
      total_training_steps: 0
    fsdp_config:
      wrap_policy:
        min_num_params: 0
      param_offload: False
      grad_offload: False
      optimizer_offload: False
      fsdp_size: -1
  rollout:
    name: vllm
    temperature: 1.0
    top_k: -1
    top_p: 0.95
    prompt_length: ${data.max_prompt_length}
    response_length: ${data.max_response_length}
    dtype: bfloat16
    gpu_memory_utilization: 0.5
    ignore_eos: False
    enforce_eager: True
    free_cache_engine: True
    load_format: dummy_dtensor
    tensor_model_parallel_size: 2
    max_num_batched_tokens: 8192
    max_num_seqs: 1024
    log_prob_micro_batch_size: 128
    log_prob_use_dynamic_bsz: ${actor_rollout_ref.actor.use_dynamic_bsz}
    log_prob_max_token_len_per_gpu: ${actor_rollout_ref.actor.ppo_max_token_len_per_gpu}
    do_sample: True
    n: 1
    n_agent: 1

retriever:
  url: "http://127.0.0.1:8000/retrieve"
  topk: 3
  dynamic_topk: False

trainer:
  nnodes: 1
  n_gpus_per_node: 8

max_turns: 10
do_search: true
